[package]
name = "ibom_splitter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ibom_splitter"

[dependencies]
anchor-lang = { version = "0.31.1" }

[features]
idl-build = ["anchor-lang/idl-build"]
